jobs:
  - job: build_infra
    displayName: Infrastructure build

    steps:
      - task: CopyFiles@2
        displayName: "Copy ARM templates"
        inputs:
          sourceFolder: infrastructure
          targetFolder: $(Build.ArtifactStagingDirectory)
      - publish: $(Build.ArtifactStagingDirectory)
        artifact: infrastructure
